# Generated by Django 3.2.8 on 2021-11-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='applieddate',
            new_name='applydate',
        ),
    ]
